### ISSUE TITLE
Make it possible to enable/disable FGD files

### ISSUE THREAD

**Issue by Qwertyus3D** [wootguy/bspguy#83] opened 2022-02-24 01:39 UTC
We can add several FGDs in Settings, it could be useful to choose which you want to enable or disable after adding them. So you can have a list of working FGDs to easily switch between them, instead of adding/deleting.

**Comment by wootguy** [comment] 2024-04-24 05:08
duplicate of #10

**Closed by wootguy** 2024-04-24 05:08 UTC
Labels: enhancement
