### ISSUE TITLE
Applying Multiple FGD Files

### ISSUE THREAD

**Issue by ToxicHolyGrenade** [wootguy/bspguy#88] opened 2022-03-31 15:44 UTC
Hello Wootguy. Would it be possible to add the possibility of using more than one FGD file? Because when trying to use more than one, it doesn't seem to work, after all when you can add another line to another FGD file. I can't add more either because as a result, the entities would look off, and I cannot easily identify what entity it is exactly. Thanks for taking the time to read.

**Comment by ToxicHolyGrenade** [comment] 2022-04-01 11:57
The sort of FGDs I am taking about basically, are game and mod FGDs, like Half-Life Absolute Zero, Opposing Force, and Afraid of Monsters: Director's Cut.

**Comment by wootguy** [comment] 2024-04-23 17:19
If the problem is that some entities don't show up, then I think that's fixed. If the problem is that multiple games define the same entity with different keyvalues and flags, then this is a duplicate of #10.

**Closed by wootguy** 2024-04-23 17:19 UTC
Labels: bug
